version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "actions"
