client:
  - any-glob-to-any-file: 'client/**'

server:
  - any-glob-to-any-file: 'server/**'

infra:
  - any-glob-to-any-file:
    - '.github/**'
    - 'docker-compose.yml'
    - 'client/Dockerfile'
    - 'server/Dockerfile'
