client:
  - changed-files:
    - any-glob-to-any-file: 'client/**'

server:
  - changed-files:
    - any-glob-to-any-file: 'server/**'

infra:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'
      - 'docker-compose.yml'
      - 'client/Dockerfile'
      - 'server/Dockerfile'
