

version: "3"

services:
  db:
    platform: linux/x86_64
    container_name: postgres-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: iwantsun
        PGDATA: var/lib/postgresql/data/pgdata

  app:
    container_name: vaycay
    env_file:
      - .env.local
    build: .
#    command: bash -c "alembic upgrade head && uvicorn vaycay/main:vaycay --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_URL=postgresql://postgres:local-password@postgres/postgres
    volumes:
      - .:/vaycay
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

  deps:
    image: tianon/true # very small image
    entrypoint: "/true"
    profiles:
      - deps
    depends_on:
      - db
