

version: "3"

services:
  db:
    container_name: vaycay
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: iwantsun
        PGDATA: var/lib/postgresql/data/pgdata

  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

