import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import importPlugin from 'eslint-plugin-import';
import prettierConfig from 'eslint-config-prettier';

export default tseslint.config(
  { ignores: ['dist', 'node_modules', 'prisma/migrations', 'nexus-typegen.ts'] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended, prettierConfig],
    files: ['**/*.ts'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.node,
      parserOptions: {
        project: './tsconfig.json',
      },
    },
    plugins: {
      import: importPlugin,
    },
    rules: {
      '@typescript-eslint/no-unused-vars': 'error',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/default-param-last': 'error',
      'no-multiple-empty-lines': 'error',
      'no-use-before-define': 'error',
      'no-duplicate-imports': 'error',
      'space-in-parens': 'error',
      'import/no-mutable-exports': 'error',
      'import/first': 'error',
      'import/prefer-default-export': 'error',
      'import/no-webpack-loader-syntax': 'error',
      'no-const-assign': 'error',
      'no-compare-neg-zero': 'error',
      eqeqeq: 'error',
      'prefer-const': 'error',
      'no-var': 'error',
      'no-new-object': 'error',
      'object-shorthand': 'error',
      'import/extensions': 'off',
      'no-prototype-builtins': 'error',
      'no-array-constructor': 'error',
      'prefer-object-spread': 'error',
      'array-callback-return': 'error',
      'prefer-destructuring': 'error',
      'prefer-template': 'error',
      'no-eval': 'error',
      'no-useless-escape': 'error',
      'func-names': 'error',
      'wrap-iife': 'error',
      'no-loop-func': 'error',
      'prefer-rest-params': 'error',
      'no-new-func': 'error',
      'no-param-reassign': 'error',
      'prefer-spread': 'error',
      'prefer-arrow-callback': 'error',
      'arrow-parens': 'error',
      'no-useless-constructor': 'error',
      'no-dupe-class-members': 'error',
      'class-methods-use-this': 'error',
      'object-curly-newline': 'error',
      'no-iterator': 'error',
      'dot-notation': 'error',
      'no-multi-assign': 'error',
      'no-case-declarations': 'error',
      'no-unneeded-ternary': 'error',
      'nonblock-statement-body-position': 'error',
      'brace-style': 'error',
      'no-else-return': 'error',
      'spaced-comment': 'error',
      'space-before-blocks': 'error',
      'keyword-spacing': 'error',
      'space-infix-ops': 'error',
      'eol-last': 'error',
      'newline-per-chained-call': 'error',
      'array-bracket-spacing': 'error',
      'block-spacing': 'error',
      'comma-spacing': 'error',
      'computed-property-spacing': 'error',
      'func-call-spacing': 'error',
      'key-spacing': 'error',
      'no-trailing-spaces': 'warn',
      'comma-style': 'error',
      semi: 'error',
      'no-new-wrappers': 'error',
      radix: 'error',
      'no-underscore-dangle': 'error',
      'no-restricted-globals': 'error',
      'no-undef': 'error',
      'new-cap': 'warn',
      'no-mixed-operators': 'warn',
      'no-nested-ternary': 'warn',
      'no-restricted-imports': 'warn',
    },
  }
);
