name: CI

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.filter.outputs.client }}
      server: ${{ steps.filter.outputs.server }}
      shared: ${{ steps.filter.outputs.shared }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            client:
              - "client/**"
            server:
              - "server/**"
            shared:
              - "package.json"
              - "package-lock.json"
              - ".github/**"
              - "lint-staged.config.js"
              - "README.md"

  client:
    name: Client - lint, type-check, format, build
    runs-on: ubuntu-latest
    needs: changes
    if: >
      github.event_name == 'push' ||
      needs.changes.outputs.client == 'true' ||
      needs.changes.outputs.shared == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install dependencies (workspace)
        run: npm ci --include=optional
      - name: Prettier check
        run: npm run -w client format:check
      - name: ESLint
        run: npm run -w client lint
      - name: Type Check
        run: npm run -w client type-check
      - name: Build
        run: npm run -w client build
      - name: Upload client build artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v5
        with:
          name: client-dist-${{ github.sha }}
          path: client/dist
          if-no-files-found: warn

  server:
    name: Server - lint, type-check, format, build
    runs-on: ubuntu-latest
    needs: changes
    if: >
      github.event_name == 'push' ||
      needs.changes.outputs.server == 'true' ||
      needs.changes.outputs.shared == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install dependencies (workspace)
        run: npm ci --include=optional
      - name: Prisma generate (ensure client/types)
        run: npm run -w server prisma:generate
      - name: Prettier check
        run: npm run -w server format:check
      - name: ESLint
        run: npm run -w server lint
      - name: Type Check
        run: npm run -w server type-check
      - name: Build
        run: npm run -w server build

  gate:
    name: Required checks
    runs-on: ubuntu-latest
    needs: [client, server]
    if: always()
    steps:
      - name: Fail if client failed
        if: ${{ needs.client.result == 'failure' || needs.client.result == 'cancelled' }}
        run: |
          echo "client job status: ${{ needs.client.result }}"
          exit 1
      - name: Fail if server failed
        if: ${{ needs.server.result == 'failure' || needs.server.result == 'cancelled' }}
        run: |
          echo "server job status: ${{ needs.server.result }}"
          exit 1
      - name: All good
        run: echo "Checks passed or were skipped."
